### ISSUE TITLE
Bug: Code blocks inside Methods are killed while transforming

### ISSUE THREAD

**Issue by umavennila** [mcuking/Vue-to-React#4]
If blocks, Switch Case blocks inside Vue component's methods are just missing after the transformation

**Comment by mcuking** [comment]
I am so sorry to reply to you too late.

I review the code and find some statements (IfStatement, SwitchStatement...) are lost in the proceed of  formatting this expression (such as  this.formModel -> this.state.formModel).

So I change the traverse visitor from statement to enter.

You can learn more about traverse in the below link.

[babel-traverse](https://babeljs.io/docs/en/babel-traverse)

**Comment by umavennila** [comment]
Thanks for the fix! Its perfect.
